### ISSUE TITLE
I have a strong feeling that it's not working. 

### ISSUE THREAD

**Issue by Minecraftian14** [John-Vision/Intel-7260-Wifi-Fix#5]
When i used fixwifi force, i patiently waited but to no avail... It's okay as long as you help me out.
102
SIOCSIFFLAGS: Operation not possible due to RF-kill
----device UP status 255
----removing device
----reprobing drivers
----pci rescan
----device is back
----rfkill unblock wireless device: 0

i just dont know one bit about ubuntu, all i did is just install it. But it doesnt seem to be able to connect to the wifi.

nickname@pcname:~$ lshw -C network
WARNING: you should run this program as super-user.
  *-network                 
       description: Ethernet interface
       product: Ethernet Connection I218-LM
       vendor: Intel Corporation
       physical id: 19
       bus info: pci@0000:00:19.0
       logical name: eno1
       version: 04
       serial: 74:e6:e2:41:d3:e7
       size: 1Gbit/s
       capacity: 1Gbit/s
       width: 32 bits
       clock: 33MHz
       capabilities: bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=e1000e driverversion=3.2.6-k duplex=full firmware=0.6-4 ip=192.168.29.114 latency=0 link=yes multicast=yes port=twisted pair speed=1Gbit/s
       resources: irq:45 memory:f7e00000-f7e1ffff memory:f7e3c000-f7e3cfff ioport:f080(size=32)
  *-network DISABLED
       description: Wireless interface
       product: Wireless 7260
       vendor: Intel Corporation
       physical id: 0
       bus info: pci@0000:03:00.0
       logical name: wlp3s0
       version: 6b
       serial: 5c:c5:d4:78:6d:ba
       width: 64 bits
       clock: 33MHz
       capabilities: bus_master cap_list ethernet physical wireless
       configuration: broadcast=yes driver=iwlwifi driverversion=5.8.0-53-generic firmware=17.3216344376.0 7260-17.ucode latency=0 link=no multicast=yes wireless=IEEE 802.11
       resources: irq:48 memory:f7c00000-f7c01fff
WARNING: output may be incomplete or inaccurate, you should run this program as super-user.

**Comment by John-Vision** [comment]
Hi there! Just to let you know, I am not really an expert on this. The solution(s) I came up with were basically a result of a lot of searching on the internet, my own tenacity, and probably a bit of luck as well. That being said, I will do my best to help you out.

I noticed a couple of things. First of all, just above "description: Wireless interface," it says "*-network DISABLED." I guess that part is pretty obvious. The other thing I noticed is where it says "version: 6b." This is different than the version on my machine, which in my case is 73. Now, I am not sure about this, but I *think* that the version *might* indicate that you have a faulty version of the 7260. (I am not sure about this, as I would need more feedback from many other users regarding this to sort it out.)

Okay, so where do we go from here? 

1.) It would be nice if you could get wifi working at least temporarily, just to show that it can work. On my laptop (an older but awesome Thinkpad T430) I actually have a little physical switch on the side which can be used to turn off the wifi. Other computers often have some sort of key combination to do the same thing - turn wifi on/off.  What type of computer do you have? Do you know, or have you checked, if your machine has any such physical switch and/or key combinations to turn wifi on/off?

2.) If you can physically open your machine, can you actually read the Model number on the 7260 card? The very best solution is to have a Model which just works. From my experience (and the reports of others) the correct Model is Model 7260HMW. (Please be very careful when opening your machine.)

**Comment by Minecraftian14** [comment]
Thanks a lot for quick response, as for now I have up and formatted the drive where I installed Ubuntu. But I am eager to try installing it again.

As a note: I installed it as a flash drive on a 32Gb SanDisk pendrive.

The laptop on which we tried installing Ubuntu already has windows 10 😅. Nothing's urgent👍.

Yeah it occurred to me also, why is it showing disabled.
rfkill list illustrated that it is hard blocked (I don't know what that means)

For whatever time i tried, I couldn't get the wifi working even once, I connected the laptop with a Ethernet cable. And there is no physical lock/key for the driver.

I don't want to open up that laptop 😅 (scary stuff) and some restrictions.


If possible,I am eager to try once again 😀.

As such, would installing Pop OS be any easier?

**Comment by John-Vision** [comment]
I don't know about Pop OS at all, but I think the 7260 (if it is the wrong Model number) has the same problem on pretty much all versions of linux. It's a linux thing, not specifically an Ubuntu thing.

Since you have Windows, I am guessing that wifi works fine on that. In which case that would rule out some physical switch on/off for the wifi.

The other thing you could try, which is certainly not as optimal, would be to get an external usb wifi. I did use that for a while myself, because I just couldn't take all the problems I was having with wifi before I finally replaced my 7260 with the right model.

**Comment by John-Vision** [comment]
By the way, what laptop do you have?

**Comment by Dumbo-AI** [comment]
patani yaar

**Comment by Dumbo-AI** [comment]
My laptop is dell latitude 3340

**Comment by John-Vision** [comment]
Check out this link for the various key combinations for your laptop:
https://www.dell.com/support/kbdoc/en-us/000132084/dell-latitude-3340-keyboard-guide

To toggle wifi on/off press Fn + PrtScr.

I am not sure if this will help you out, but it's worth trying.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Dumbo-AI** [comment]
Sadge, i deleted ubuntu like right 2 hours ago, but I'll download again to try that

**Comment by John-Vision** [comment]
Not sure who Sadge is, lol, but okay.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Dumbo-AI** [comment]
Oh lol,it's just another way to say sad

**Comment by Minecraftian14** [comment]
Nah,I guess that won't really work because
- there ain't any physical switch, as the same device find windows with wifi without any changes.
-a keyboard shortcut for that would be firmware specific, this working only on windows.

I had a doubt though. The laptop once had many restrictions set on it due to company provided laptop terms. However it has been formatted after that many times, I doubted there still might be something lurking inside.

And then I had a question. Can I, if easy, obtain the driver from windows, decompile it, load it to Ubuntu, then compile it there...

Thanks a lot for the support 😊

**Comment by John-Vision** [comment]
The keyboard shortcut might be a bios thing and therefor work for any operating system installed - but I don't know, I am really not an expert at this.

As for using the Windows driver in Linux, there is a project called "Ndiswrapper" that let's you do that, without the compiling/decompiling, but I don't really know too much about that either, or if if will work well with the 7260.

If this is a work-provided laptop, and you cannot change the wifi card, and you also want to use Linux (and wifi rather than ethernet) you DO have the option of getting an external USB wifi adapter. These actually work great. I bought and used one myself for a while while I was having basically the same problem as you. The only downside is that you'll have something sticking out of a USB port. Some of these, however, are built to be "low-profile" so they don't stick out too much. If you don't mind having a big ol' antenna sticking out and want something really high-powered, those are available too.

An external USB wifi might be your best solution at this point.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Minecraftian14** [comment]
i guess i quit...
what about this issue; close it?

**Comment by John-Vision** [comment]
Yes, I will close it.
